name: indent

on: [push, pull_request]

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

permissions:
  contents: read

jobs:
  indent:
    # run the indent checks

    name: indent
    runs-on: [ubuntu-22.04]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 100
    - name: setup
      run: |
        ./contrib/utilities/download_clang_format
    - name: indent
      run: |
        ./contrib/utilities/check_indentation.sh

  doxygen:
    # build the documentation

    name: doxygen
    runs-on: [ubuntu-22.04]

    steps:
    - name: setup
      run: |
        sudo apt update
        sudo apt install graphviz perl texlive-bibtex-extra
    - uses: ssciwr/doxygen-install@v1
      with:
        version: "1.9.6"
    - uses: actions/checkout@v4
    - name: build documentation
      run: |
        mkdir build
        cd build
        cmake -DDEAL_II_COMPONENT_DOCUMENTATION=ON -DDEAL_II_DOXYGEN_USE_MATHJAX=ON ..
        make -j 2 documentation
    - name: check for doxygen errors and warnings
      run: |
        cd build
        cat doxygen.log
        # Suppress:
        # warning: Inheritance graph for 'SmartPointer' not generated, too many nodes (138), threshold is 50. Consider increasing DOT_GRAPH_MAX_NODES.
        # warning: Inheritance graph for 'Subscriptor' not generated, too many nodes (209), threshold is 50. Consider increasing DOT_GRAPH_MAX_NODES.
        sed -i '/Inheritance graph/d' doxygen.log
        # Suppress:
        # warning: explicit link request to '<function>' could not be resolved
        sed -i '/explicit link request to/d' doxygen.log
        # Remove empty lines
        sed -i '/^$/d' doxygen.log
        # Check if remaining log is zero size
        ! [ -s doxygen.log ] || exit 1
    - name: compress
      run: |
        tar -czf doxygen_documentation.tar.gz build/doc/doxygen
    - name: archive documentation
      uses: actions/upload-artifact@v4
      with:
        name: doxygen_documentation.tar.gz
        path: doxygen_documentation.tar.gz

  typos:
    # check for typos

    name: typos
    runs-on: [ubuntu-22.04]

    steps:
    - uses: actions/checkout@v4
    - uses: crate-ci/typos@v1.24.1
      with:
        files: doc examples include source tests
        config: ./.typos.toml
